version: "3"
services:
  bot:
    container_name: pornhubgif_bot
    image: lereverandnox/pornhubgif_bot
    environment:
      - TELEGRAM_API_TOKEN=$TELEGRAM_API_TOKEN
      - ENVIRONMENT=$ENVIRONMENT
