version: '2'
services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_API_TOKEN=$TELEGRAM_API_TOKEN
      - ENVIRONMENT=$ENVIRONMENT
    ports:
      - $BOT_PORT:8080/tcp
