version: '2'
services:
  bot:
    build: .
    # restart: unless-stopped
    volumes:
      # DEV PURPOSE ONLY
      - ./src:/app
    environment:
      - TELEGRAM_API_TOKEN=$TELEGRAM_API_TOKEN
      - ENVIRONMENT=$ENVIRONMENT
    ports:
      - $BOT_PORT:80/tcp
